title: Cedarview Aliance Church
description: A church website.

url: "https://s-laugh.github.io"
baseurl: /cedarview
color-scheme: "#0b2736" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
